### PR TITLE
Add timeout option to specify ssh_timeout via wrapacker

### PR DESCRIPTION
**Pull request by cosmo0920**
I added `--timeout` option to specify the amount of time `ssh_wait_timeout` via `wrapacker`.
And I make longer `ssh_wait_timeout` by default.

How about this approach?
 
Related to #8.

### CODE REVIEW

**Comment by tomswartz07** [comment]
I like the idea, and it will solve a number of instability/repeatability issues.

@cosmo0920 Have you consistently had success with the 15m timeout?
It seems like a minor quibble, however: in my [personal fork](https://github.com/tomswartz07/packer-arch/blob/master/arch-template.json#L27), I've had great luck with 20 minutes, even with super slow mirrors, installing many extra packages, et. al.

**Comment by elasticdog** [comment]
Nice work @cosmo0920, this looks fantastic! My only comment is that `ssh_wait_timeout` appears to be deprecated in favor of just `ssh_timeout`...per poking around the packer codebase, [this comment](https://github.com/mitchellh/packer/blob/024132a698092b0d950d0aaffdb8821616de6a72/builder/virtualbox/common/ssh_config.go#L18-L21), and the [communicator documentation](https://packer.io/docs/templates/communicator.html#ssh_timeout). If you can make that change, I'd be glad to merge this in.

The default is only `1m`, right? I'm fine with either `15m` or `20m` as the default, if you and @tomswartz07 have been experiencing things taking that long.

Thank you for the contribution!

**Comment by cosmo0920** [comment]
Thanks for reviewing.
I used `ssh_timeout` instead of `ssh_wait_timeout`.

**Comment by cosmo0920** [comment]
> The default is only 1m, right? I'm fine with either 15m or 20m as the default, if you and @tomswartz07 have been experiencing things taking that long.

It seems that current packer master's default is 5m: https://github.com/mitchellh/packer/blob/268ce81dd3874822c8afa221e8bd1f8da35fa534/helper/communicator/config.go#L83

But this is too short to complete creating vagrant arch box.

> Have you consistently had success with the 15m timeout?
It seems like a minor quibble, however: in my personal fork, I've had great luck with 20 minutes, even with super slow mirrors, installing many extra packages, et. al.

My experience is enough waiting time around 15m when I use `jaist mirror` in Japan.

But we should consider super slow mirrors in wrapacker.
Now I decide to use `20m` for default value.

**Comment by cosmo0920** [comment]
Any concerns?
If there are no any concerns, I will squash this PR commits and commit at master tomorrow.

**Comment by elasticdog** [comment]
Looks great, I'd say :shipit: !

**Comment by elasticdog** [comment]
Thanks again @cosmo0920...I'm thick-headed and for whatever reason never groked what the issue was in #8, so it had been left for entirely too long.

**Comment by cosmo0920** [comment]
Awesome!

**Pull request closed without merging**
