### PR TITLE
Improve disk compaction

### PR DESCRIPTION
**Pull request by appleby**
This pull-request adds a new provisioner script which is intented to reduce the final size of the box artifact.

The script does a final clean of the pacman cache, then writes zeros to a file until the filesystem is full and unlinks the file. A similar strategy is used in the hashicorp/atlas-packer-vagrant-tutorial repo, here:

https://github.com/hashicorp/atlas-packer-vagrant-tutorial/blob/master/scripts/zerodisk.sh

With this change, the box file was reduced by ~150MB in my build.

```
$ du -hs output/packer_arch_virtualbox.box
441M    output/packer_arch_virtualbox.box
```

The current revision only runs the cleanup script for the virtualbox-iso build because that is the only builder I can test on my local machine. However, I did push a similar build to Atlas and was able to verify that the vmware-iso box is similarly reduced in size. I'm not able to test the parallels builder.

Note that the pacman cache is now being cleaned twice in the virtualbox-iso build. Once at the end of install-base.sh and once in cleanup.sh. If testing reveals that cleanup.sh works for all three builders, you could potentially remove the pacman cache clear from install-base.sh and just enable cleanup.sh for all the builders.

### CODE REVIEW

**Comment by cosmo0920** [comment]
LGTM. :+1:

**Comment by tomswartz07** [comment]
I say: :shipit:

**Comment by elasticdog** [comment]
Awesome! It should be safe to apply this to any of the builders (I'll remove the conditional). I plan on adding a few other cleanup items (minor logs/history removal and whatnot), but this will definitely have the biggest win. Thank you!

**Comment by elasticdog** [comment]
...and actually now that I poke around the filesystem, there's really not much else we can do (we already use tmpfs for /tmp, have no swap, etc). The remaining things like journalctl are already minimal, and logs like lastlog are sparse, so also tiny. I'll add in a `pacman-optimize` for good measure before zeroing out the drive, but I think that's about all that applies.

**Comment by appleby** [comment]
Thanks for the quick response and merge.

Let me know if you want me to submit another pull-request that removes the `pacman -Scc` from `install-base.sh`.  It's not hurting anything, but might shave a few seconds off the install time.

**Comment by elasticdog** [comment]
@appleby I went ahead and removed the duplication via 266dd4ea6cd8facbeff4bdaa14e69fe59fbd226a. FYI, your change made a huge difference and my last image size was 435 MB...so much awesome.

**Comment by tomswartz07** [comment]
Working great. I have similar results: 434MB box image, about 150MB of savings. 

Nice work, @appleby

**Comment by appleby** [comment]
Awesome, glad to hear it's working.  Thanks for the feedback, and thanks for packer-arch!

**Pull request merged**
